### PR TITLE
Add typedoc

### PR DESCRIPTION
**Pull request by brandones**
Automatic API documentation! :tada: 

Just need to follow [this howto](https://github.blog/2016-08-22-publish-your-project-documentation-with-github-pages/) and then add a link to the page in the README once this is merged.

### CODE REVIEW

**Comment by FlorianRappl** [comment]
Quick question: What's the value add here? Because as it stands its output is an HTML file - which cannot be viewed so directly on GitHub. If it would be a Markdown, the situation is different.

If I'll need to clone this to view the file properly, then I can also open VS Code and I get type completion with everything out of the box (and always up-to-date).

Maybe https://github.com/tgreyuk/typedoc-plugin-markdown should be used.

**Comment by brandones** [comment]
The article I link suggests GitHub pages. It says you just have to point the repo’s pages setting at “docs/“ and it’s done.

But yeah, maybe a Markdown page would be more accessible or easier to manage. I’ll run that plugin.

**Comment by FlorianRappl** [comment]
GH pages would also work for me, however, usually requires a bit of setup (e.g., either a gh-pages branch or some custom configuration) and would have a strange URL as we don't have the primary GH pages repository here.

Therefore my assumption was that in the usual flow people would go in here (i.e., the repository) first anyway.

**Comment by brandones** [comment]
I mean, I figure the API docs will be separate from the main readme, linked from the top? (But as a markdown page, anyway)

**Comment by FlorianRappl** [comment]
> I mean, I figure the API docs will be separate from the main readme, linked from the top?

Sure. I agree.

**Comment by jonathandick** [comment]
LGTM

**Comment by brandones** [comment]
Actually, the Markdown version doesn't look quite as nice, so it didn't seem worth switching from HTML unless I could integrate it into the README. So I did. Please take a look.

**Pull request merged**
